---
abstract: 'A module to parse the output of git-fast-export'
author:
  - 'Philippe Bruhat (BooK) <book@cpan.org>'
build_requires:
  Cwd: '0'
  File::Path: '0'
  File::Spec: '0'
  File::Temp: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::Git: '0'
  Test::More: '0.88'
  Test::Script: '1.05'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.016, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Git-FastExport
requires:
  Carp: '0'
  File::Basename: '0'
  File::Spec::Functions: '0'
  Getopt::Long: '0'
  Git::Repository: '0'
  List::Util: '0'
  Pod::Usage: '0'
  Scalar::Util: '0'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Git-FastExport
  repository: http://github.com/book/Git-FastExport.git
version: '0.105'
