---
name: Git-FastExport
version: 0.04
author: []
abstract: A module to parse the output of git-fast-export
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Git: 0.01
provides:
  Git::FastExport:
    file: lib/Git/FastExport.pm
    version: 0.04
  Git::FastExport::Block:
    file: lib/Git/FastExport.pm
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
